### ISSUE TITLE
does this ever vTaskDelay?

### ISSUE THREAD

**Issue by btsimonh** [256dpi/esp-mqtt#25] opened 2018-11-21 16:24 UTC
Hi, 
Does this ever vTaskDelay once successfully connected and then sitting there waiting for data?
I could not track down where it gives up it's timeslice, and did get (once):
```
Task watchdog got triggered. The following tasks did not reset the watchdog in time:
 - IDLE (CPU 1)
Tasks currently running:
CPU 0: IDLE
CPU 1: esp_mqtt
␛[0;31mE (707191) esp_mqtt: lwmqtt_keep_alive: -13␛[0m
```
and am having real trouble with mqtt disconnects (-13 and -4).

However, having added
```
    } else {
      // no data available, so
      // delay loop by 10ms and yield to other processes
      vTaskDelay(10 / portTICK_PERIOD_MS);
    }
```
on the end of if (available), I now longer get any regular mqtt disconnects....

s

**Comment by 256dpi** [comment] 2018-11-22 18:12
It does. The mutex locks and unlocks, and selects on the socket will yield to other tasks until data is available or the mutexes are accessible. I never ran into issues with the watchdog until now.

Is it possible that your connection is very unstable? The errors -13 (pong timeout) and -4 (network timeout) suggest that the client waited a long time for data that didn't arrive in time.

**Comment by btsimonh** [comment] 2018-11-22 18:58
it's strange; subscribing takes seconds most times.  But the server (mosquitto) logs indicate immediate response. The esp was about 3m from the switch.
Subsequent to the above, I do have disconnects.  I think it's an interaction between different threads (tasks) in esp.  As soon as I enabled many subscriptions again (5), it started failing.  I'd disabled a lot of the functionality to diagnose.... the app can have MANY subscriptions (40+).
I put some external protection around MQTT activity as well as your mutexes, and it still showed issues.

have to say, this is my first esp32 try, so learning all the time.  
App is https://github.com/btsimonh/esp32-ble2mqtt/tree/btsimonh-platformio2
it involves BLE, so I'm on esp-edf 3.1.1 (in theory), and the BLE/wifi interaction could be an issue.  Seems we're on bleeding edge with esp32 and BLE.

ref your reply;
when subscribing, it calls ***_until with available=0
Are you SURE that this will not tight loop until a packet comes in?

**Comment by 256dpi** [comment] 2018-11-30 22:18
I suspect these issues are caused by another component in your project.

The call to `lwmqtt_cycle_until` caused by a subscribe will block as the underyling read operation will block.

**Comment by 256dpi** [comment] 2019-02-01 07:45
I will close this for now, please reopen if there is still an issue.

**Closed as completed by 256dpi** 2019-02-01 07:45 UTC
